### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by Eitot** [scour-project/scour#112]
I’m so in the habit of checking `man` that I miss it for Scour. Some of the options in `--help` are not spelt out and a wee commentary for some options would be nice. An example section would also be useful and perhaps some niche options and the copyright stuff could be moved from `--help` to the man page.

How would you feel about adding one? I see that it is as easy as adding a `data_files` parameter to setup.py which installs the man page in the correct directory upon install with `pip`.

**Comment by Ede123** [comment]
We definitely want to [improve the project's README](#29) and should add some real documentation.

However I doubt man pages are the correct way to distribute this documentation since I got the feeling they are very uncommon in the Python ecosystem, especially for packages distributed via PyPI. Tobias just suggested [readthedocs.org](https://readthedocs.org/) to publish documentation and I'd prefer that idea.

@oberstet: In case somebody should ever find any time to actually write some documentation, do you think man pages are worth investigating? [Sphinx](http://www.sphinx-doc.org/en/stable/man/sphinx-build.html) seems actually be able to build man pages, so it might be possible with an acceptable amount of effort, but I'd say man pages are too specific to the *nix world to be generally useful.

**Comment by oberstet** [comment]
Man pages are "unusual" for Python projects distributed via PyPI, and problematic, since they need to be installed into system directories. Sometimes, distro packagers add man pages when packaging Python stuff into deb/rpm etc., and that is "ok" (but not our task). 

I have strong opinions rgd distro packaging of Python stuff: it is plain wrong. Installing everything into the system/global Python is wrong - conflicting versions, interference between packages etc

That being said, I agree with @Eitot that `--help` should spell out all command line options, precisely and exhaustively. It sucks a little having to dig into source to get at the real stuff.

As a user, this would be my expectation of docs in general:

* there should be a concise README in the repo that is duplicated to appear as the PyPI page. Contents: what is it? why/for what use? what license / where did it came from (history). pointers to: source code, changelog, issue tracker, how to get in touch (contacts), docs (readthedocs)
* `--help`: concise, exhaustive command line usage/options
* readthedocs: tutorial like .. use case oriented. should we officially support API based usage, that too (API reference)

Sphinx is great .. the way to go IMO. Hosting: RTD generated from Sphinx. This can be fully automated (we can have RTD integrated, and online docs will be automatically updated). RTD is the go to place looking for Python docs.

---

Rgd CLI of Scour: currently we use `optparse` (Py stdlib). This is old, `argparse` (Py stdlib) is better and the new way. 

> Deprecated since version 2.7: The optparse module is deprecated and will not be developed further; development will continue with the argparse module.

Apart from argparse, we might also consider http://click.pocoo.org/. This can do very nice CLIs - though it would introduce a non-stdlib dep.

**Comment by Eitot** [comment]
While unusual, they are used. `youtube-dl` is an example. I have no objections to a documentation webpage, I actually think we should definitely do this, but I prefer to have documentation in the CLI too. This is how most Unix CL programs are distributed and I am of the opinion that Scour should be a good citizen when it can be invoked as a CL program, even when written in Python. The user probably does not care about the programming language after all.

Man pages do not need to be installed in system locations, they can be installed in local environments too. Where Scour itself is installed is ultimately the choice of the user. If `pip install` installs the `scour` binary into`/usr/local/bin`, then the man page is installed in `/usr/local/share/man`. Similarly, if `pip install --user` installs the binary into `~/.local/bin`, then the man page goes into `~/.local/share/man`. Even installing it within `virtualenv` is supported without problems. `pip` supports the installation of additional files and handles the installation _and_ removal. In my own tests, all that was required was adding `data_files=[('scour.1', ['share/man/man1/scour.1'])]` to `setup.py`. `pip` then determines the top-level directory upon installation, just as it does for the binary file. It is even possible to override the data path with `pip --install-option`. `man` itself searches for man pages automatically if the `$PATH` is set correctly.

As Ede123 said, Sphinx can handle both at the same time. I think Scour would benefit from having a fleshed-out man page. I myself tested the man-page functionality with a Ruby program called [RONN](http://rtomayko.github.io/ronn/), which takes a markdown file and produces a correctly-formatted man page as well as an HTML page of it. It is an alternative to think about to the more complex Sphinx.

Is `argparse` worth sacrificing Python 2.6 support? I looked at it a couple of weeks ago and it wasn’t clear to me what kind of functionality it adds that would be useful for Scour.

**Comment by oberstet** [comment]
> Is argparse worth sacrificing Python 2.6 support?

Scour does not support 2.6 anymore. argparse is in the stdlib.

> I prefer to have documentation in the CLI too.

A CLI help text should be concise, simply listing options. It should not be a multi-page full documentation.

> RONN

No, I wouldn't support that. Sphinx is standard in Python, trivial to use, and Ruby sucks.

**Comment by Eitot** [comment]
This project is not seeking to _actively_ drop support for Python 2.6 though. This is what replacing `optparse` with `argparse` would do if it does not provide a clear benefit for it. Which functionality or improvement would `argparse` add for Scour that would make the actual discontinuation of Python 2.6 worth it?

A man page is not the same as `--help`, they are complementary. `--help` is supposed to list commonly-used commands for quick reference. A man page is a complete documentation for the CL program. They co-exist, just as a man page and a web-based documentation can co-exist. Sphinx is capable of producing both webpages and man pages from the same source material.

Sphinx is not trivial to use and it may even be overkill for this purpose, hence why I suggested a simpler alternative just for generating a man or HTML page. It does not need to be comprehensive, given that Scour is not such a complex program. That RONN is written in Ruby is beside the point, the produced documentation itself is not written in Ruby.

**Comment by oberstet** [comment]
As said, I won't support RONN.

Python 2.6 support already **is** dropped (there is syntax in the repo which won't run on 2.6). Anyway, I don't have time for this.

**Comment by Ede123** [comment]
`argparse` discussion is off topic here and since I don't see any direct advantages of a switch either, anda switch would actually require some effort (`optparse`and `argparse` are not API compatible) I don't think this is something we need to bother with any time soon...

Regarding manpages: Wether or not we actually add man pages is not a useful discussion at this point, since we don't even have any content to put in a man page yet. Let's first think about proper documentation (via `sphinx` and published on readthedocs).

If at some point we have completed docs we coul revisit this, but I'm with Tobias here and don't like the idea of adding arcane documentation native to only some ecosystems and hassling with proper installation of those features without breaking what packagers might have done already. (If you check out the Debian package for scour-python, you'll see they already install man pages).

**Comment by Ede123** [comment]
Follow up on documentation is #116.

**Comment by Eitot** [comment]
> Anyway, I don't have time for this.

I find it disappointing how my attempts to discuss this are simply brushed off like this, I was willing to contribute with documentation and was looking for options on how to do this. My last PR to the readme was also reversed with no explanation. I will not be following this project anymore.

**Comment by oberstet** [comment]
@Eitot Your PR to the README was merged: https://github.com/scour-project/scour/pull/36. As far as I can see, 4 out of 5 of your PRs have been merged. The one not merged is this https://github.com/scour-project/scour/pull/42. And I gave a reason of why not. Which PR / changes to the README did you have that wasn't merged?
