### ISSUE TITLE
Release managing

### ISSUE THREAD

**Issue by oberstet** [scour-project/scour#142]
@Ede123 last release on PyPI was 0.35 (https://pypi.python.org/pypi/scour), but you've been quite active over the months;) Do you want admin role on scour on PyPI so you can push releases?

If so, what is your PyPI handle?

Note to self: https://pypi.python.org/pypi?:action=role_form&package_name=scour

**Comment by Ede123** [comment]
Hi Tobias, sure, handle is "Ede_123". Safes us both some effort as I don't have to bug you whenever I think it's a good time for a new release 😉 

A new 0.36 release is in fact due soon. I just wanted to give the recent precision changes a little testing time and also look into the [last remaining filed bug](https://github.com/scour-project/scour/issues?q=is%3Aissue+is%3Aopen+label%3Abug) if time permits.

Long term goal for me would be to finalize #121 / fix #119 (add API) and then release version 1.0.0 (and switch to semantic versioning) once finished. (Will still take some time and thought though, i.e. I already changed my mind again since doing the PR).

**Comment by oberstet** [comment]
Sounds cool! I've given you "Maintainer" role on Scour/PyPI, which allows you to push new releases. If it doesn't work, feel free to reopen ..

**Comment by Ede123** [comment]
Just pushed Scour 0.36.

Seems to have worked fine (except for some issues with pushing the package, likely due to https://github.com/pypa/setuptools/issues/941).

Hope I didn't miss anything...

**Comment by oberstet** [comment]
Looks good! It is avail on https://pypi.python.org/pypi/scour
