### ISSUE TITLE
running scour multiple times, leads every second time to the same size

### ISSUE THREAD

**Issue by JoKalliauer** [scour-project/scour#186]
I run scour multiple times since it reaches a static size, but I already had several files where scour switches between two (or three) different sizes.

I sometimes run scour with all options enabled.
> scour -i input.svg -o output.svg --enable-comment-stripping --remove-titles --remove-descriptions --disable-embed-rasters --strip-xml-space  --create-groups --remove-metadata --remove-descriptive-elements --renderer-workaround  --enable-viewboxing --enable-id-stripping --shorten-ids --set-precision=5 --set-c-precision=3

373750 bytes:
[First.svg.txt](https://github.com/scour-project/scour/files/1905018/First.svg.txt)

373560 bytes:
[Second.svg.txt](https://github.com/scour-project/scour/files/1905019/Second.svg.txt)

373750 bytes:
[Third.svg.txt](https://github.com/scour-project/scour/files/1905020/Third.svg.txt)

Copyright: Public Domain by grnsgrf
scource: https://commons.wikimedia.org/wiki/File:Welcome_to_Fabulous_Las_Vegas_Sign.svg

**Comment by nthykier** [comment]
Based on a wdiff, the concrete case appears to be caused by --shorten-ids.  The IDs are not stable and are apparently not always optimal.

**Comment by nthykier** [comment]
@JoKalliauer - which version of scour were you using for this test? 0.36?

**Comment by nthykier** [comment]
Hmm, v0.35 does not recognise --set-c-precision=3 and I cannot reproduce it with a git checkout of v0.36 nor master@6ea126d290e29c990244d9df17f00f84b7c07108.  For me, scour on the first fine consistently generate the same output (bit-for-bit identical) even if I change version (v0.36 vs. master) or python (2.7 vs. 3.6.5rc1)

**Comment by Ede123** [comment]
The problem is that IDs get are generated in a way that gives elements with the most references the shortest IDs. When running the second time on an already processed file the shortest IDs are therefore already "taken" and replaced with potentially longer ones.

What we need to do is assign "temporary" IDs to all elements and/or exchange IDs when necessary, but it needs some investigation on how to do this efficiently.

**Comment by nthykier** [comment]
Ack, I am playing with the code right now to see if I can solve it.

**Comment by nthykier** [comment]
Btw, with this particular input file, I see a factor ~7 different in runtime depending on python version (py2: ~16s, py3: ~2.5s).

@Ede123: Should we promote / document that people might find the python3 version significantly faster than python2? E.g. in the README.md file?

**Comment by JoKalliauer** [comment]
@nthykier  If you still need an answer: I used scour 0.36, Python 2.7 (in Cygwin on Windows 10).

@nthykier & @Ede123  : I think you might should recommend Inkscape to change from Python 2.7 to Python 3.x. (For saving as an optimized svg.)

**Comment by Ede123** [comment]
@nthykier Might make sense... When I first started working on Scour (probably sometime when Python 3.3 was current) but nowadays the difference seems significant (I hope we did not regress Python 2.7 performance at some point...).

@JoKalliauer We can not simply "choose" to use Python 3.x in Inkscape as a lot of the bundled extensions are not compatible yet. However efforts are currently underway to change this.

**Comment by nthykier** [comment]
Eduard Braun:
> @nthykier Might make sense... When I first started working on Scour (probably sometime when Python 3.3 was current) but nowadays the difference seems significant (I hope we did not regress Python 2.7 performance at some point...).
> 

I believe that most of the performance difference are due to changes in
python3 itself (without any tests to back this claim).  I had a look at
the release notes for python 3.4 - 3.6 and there I found:

 * The property() getter calls are up to 25% faster. (Contributed by Joe
   Jevnik in bpo-23910.) [py3.5]

   - This affects many of our calls to the DOM.  A method like
     getAttributeValue, which is the "top 2 in total time" for
     "example.svg" in LP#490197 (imported as GH#77), uses a
     property()-generated getter on the underlying Attr object
     (and it is not the only affected method).

 * The Python interpreter now uses a 16-bit wordcode instead of bytecode
   which made a number of opcode optimizations possible. (Contributed by
   Demur Rumed with input and reviews from Serhiy Storchaka and Victor
   Stinner in bpo-26647 and bpo-28050.) [py3.6]

   - This is just a general speed improvement all around.

Note that in my tests, I have used python 3.6 for python3.  It would be
interesting to see how python 3.3 compares (but I do not have that
installed).

Thanks,
~Niels

[py3.5]: https://docs.python.org/3/whatsnew/3.5.html#optimizations

[py3.6]: https://docs.python.org/3/whatsnew/3.6.html#optimizations

**Comment by oberstet** [comment]
general thoughts on above discussion:

* bothering about Py 3.3 and 3.4 isn't worth IMO. for Py 3, we should go for Py 3.5+
* for users with 1000s of SVGs, running on PyPy (when we had batch mode) and/or parallelize (use a build tool -- why bother with multi-process orchestration in Scour when `make -jN` can do?)

**Comment by JoKalliauer** [comment]
Thanks to  @nthykier : I can confirm it is fixed.
