### ISSUE TITLE
file size reduction

### ISSUE THREAD

**Issue by adammaj1** [scour-project/scour#238]
Hi
I have 80 MB svg file. After maximal scrubbing the file has 87% size. Are ther any options to reduce it more ?  Commons  have limit 10 MB : https://commons.wikimedia.org/wiki/Commons:Maximum_file_size

TIA

**Comment by JoKalliauer** [comment]
Commons **had** a limit till 2016 of 10MB, but larger files are still undesired. 

You can increase the filereduction in using more strict lossy file-reduction such as
`scour -i input.svg -o output.svg --enable-comment-stripping --remove-titles --remove-descriptions --disable-embed-rasters --strip-xml-space  --create-groups --remove-metadata --remove-descriptive-elements --enable-id-stripping --shorten-ids --set-precision=3 --set-c-precision=2 --error-on-flowtext --no-line-breaks --indent=none`
But expect damages and visible lossyness with this option


@adammaj1 : You could try additionally other optimizers such as https://github.com/RazrFalcon/svgcleaner and https://github.com/svg/svgo or reduce the number of nodes using Inkscape see https://commons.wikimedia.org/wiki/User:JoKalliauer/Optimization#Using_Optizatiors

I use https://github.com/JoKalliauer/cleanupSVG/blob/master/NFC.sh for file-size reduction

Generally if a file is so large you did something "wrong" in creating, I think you should post this question on https://commons.wikimedia.org/wiki/Commons:Graphic_Lab/Illustration_workshop and imho not here.

Some recommendations:
- do not use rastergraphics
- do not use autotrace
- use a meaningfull precision (e.g. reduce the number of nodes)
- use <use>
- Do not use unvisible details (e.g. not evey border of every townshipt in a map of a whole country)

**Comment by adammaj1** [comment]
Thx.
The png version of the file and the code is hrere: https://commons.wikimedia.org/wiki/File:Graph_of_sin(exp(x))_function.png

I probably used too precise scanning:
x=0.0:0.000001:5.0;

**Comment by JoKalliauer** [comment]
@adammaj1 : I do not have the problem with MatlabR2019b, with print('-dsvg','Graph of sin(exp(x)) function.svg'). My file is 41 KB large.

PS I'm a user (not a developer)

**Comment by adammaj1** [comment]
using the ssmae settings ? x=0.0:0.000001:5.0;
?

**Comment by JoKalliauer** [comment]
@adammaj1 

I just run
```
x=0.0:0.00000001:5.0;
plot(x,sin(exp(x)));
xlabel("x");
ylabel("sin(exp(x))");
title("Graph of function sin(exp(x))");
print('-dsvg','Graph of sin(exp(x)) function7.svg')
```
and got a file of [88KB](https://upload.wikimedia.org/wikipedia/commons/archive/b/bc/20200316195534%21Graph_of_sin%28exp%28x%29%29_function.svg), and optimized it to [16KB](https://upload.wikimedia.org/wikipedia/commons/b/bc/Graph_of_sin%28exp%28x%29%29_function.svg) (without reduding nodes, keeping linebreaks, adding doctype-definition)


increasing the precission reduces the unedited file-size from Matlab (because smother line)
|precisission|unoptimized file-size|
|---|---|
|x=0.0:0.001:5.0;|124kB|
|x=0.0:0.0001:5.0;|98kB|
|x=0.0:0.00001:5.0;|98kB|
|x=0.0:0.000001:5.0;|93kB|
|x=0.0:0.0000001:5.0;|88kB|
|x=0.0:0.00000001:5.0;|88kB|

@adammaj1 please disscuss it at https://commons.wikimedia.org/w/index.php?title=File_talk:Graph_of_sin(exp(x))_function.svg it is a problem how you created the file not how it is optimized.

**Comment by adammaj1** [comment]
OK. Thx
