### ISSUE TITLE
Support for (adding) explicit width/height attributes

### ISSUE THREAD

**Issue by bllngr** [scour-project/scour#240]
Some applications have issues with SVGs that do not specify explicit `width`/`height` attributes (e.g. Madcap Flare). For those, it would be helpful if those attributes could be added if not present.

So, this would basically be the opposite of the `--enable-viewboxing` feature. Maybe both could be supported, resulting in explicit `width`/`height` *and* a `viewBox` attribute.

Or maybe `--renderer-workaround` could be changed to add those attributes?

**Comment by JoKalliauer** [comment]
@bllngr  (I'm just a stupid user, not the developing.)

Why should it be a renderer-workaround?

librsvg, resvg, Inkscape, Chrome/Chromium, Firefox, Adobe Illustrator render them correctly if it cotains a viewBox, therefore it is a imho just a waste of bytes. Adding width/height for files without viewBox might be too complicated.

svgo (or [SVGOMG](https://jakearchibald.github.io/svgomg/)) has the opposite options:
`--enable=removeViewBox`
`--enable=removeDimensions`

**Comment by Ede123** [comment]
The problem here is that we'd have to guess a size for the SVG - which we really can't.
We can assume px or mm or ... but it would all be arbitrary.

Furthermore we'd modify the SVG, as the default for width/height is "100%", and a standard compliant renderer tries to scale the SVG to fill the whole view-port when rendering it.

Last but least - considering Scour is an SVG optimizer and not an "SVG compatibility fixer" - such an implementation would be out of scope and actually against the goals of Scour, as it increases file size as Johannes mentioned.

At this point I'm afraid I have to close this as wontfix, as the whole point of the feature seems to be to workaround issues in other software.

**Comment by JoKalliauer** [comment]
> 
> 
> Some applications have issues with SVGs that do not specify explicit `width`/`height` attributes (e.g. Madcap Flare). For those, it would be helpful if those attributes could be added if not present.
> 
> So, this would basically be the opposite of the `--enable-viewboxing` feature. Maybe both could be supported, resulting in explicit `width`/`height` _and_ a `viewBox` attribute.
> 
> Or maybe `--renderer-workaround` could be changed to add those attributes?

@bllngr I kind of did not read that you provied Madcap Flare as an example.


However you could use [sed](https://en.wikipedia.org/wiki/Sed):
`sed -ri 's/<svg([-[:alnum:]=\" .\/\:,\(\)_#]+) viewBox="([-[:digit:]\.]+) ([-[:digit:]\.]+) ([-[:digit:]\.]+) ([-[:digit:]\.]+)"([-[:alnum:]=\" \.\/:\,\(\);#]*)>/<svg\1 viewBox="\2 \3 \4 \5"\6 width="\4" height="\5">/' filename.svg`

I did not test it, but I assume it works.
