### ISSUE TITLE
Option to remove descriptive elements

### ISSUE THREAD

**Issue by Eitot** [scour-project/scour#38]
Following up on #35, I found that `<title>` and `<desc>` (as well as `<metadata>`) are purely descriptive elements, according to the [SVG 1.1 specification](http://www.w3.org/TR/SVG/intro.html#TermDescriptiveElement). There already is an option to remove `<metadata>` (`--remove-metadata`), but not for `<title>` and `<desc>`.

What we could do:
1.  Add `<title>` and `<desc>` to the same option.
2.  Add a new option that removes them (either separately or together).

Any thoughts?

**Comment by Ede123** [comment]
This is not an easy decision. On one hand it would probably be sufficient for most users to offer just one option to strip all of the descriptive elements.

On the other hand I'm almost certain there might be border cases were people might want to strip `<metadata>` but keep a `<title>` (and potentially a `<desc>`) if present.

While I would tend towards offering separate options for this very reason I'm also afraid that Scour already has too many options and adding even more might over-complicate things. (Also note that the options are named inconsistently, e.g. `--remove-metadata` vs. `--enable-comment-stripping` vs. `--strip-xml-prolog` and to make it even harder some default-on options have to be disabled specifically while some default-off options have to be enabled specifically and some options even offer redundant switches for both which makes it very hard to see through the system for starters... this might actually be worth some refactoring in future and another bug).


Anyway to stay on topic I'd prefer not to use `--remove-metadata` for `<title>` and `<desc>` elements (simply because of the name) but would prefer to either

1. Add specific options for both (e.g. `--remove-title` and `--remove-desc`) or
2. Add an option that removes all descriptive elements (e.g. `--remove-descriptive-elements`)

Actually 1. and 2. could be combined (i.e. `--remove-descriptive-elements` could simply enable all three: `--remove-metadata`, `--remove-title` and `--remove-desc`.

**Comment by Eitot** [comment]
These are great suggestions. I’m in favour of your solution, i.e. add options for each type next to the existing ``--remove-metadata`` and add a collective option to remove all three.

I just want to add that the ``--help`` output doesn’t need to list all of the options, in my opinion, just the more common ones. Perhaps we could add a separate command to list all options for those that need them.
